from aiogram.types import ReplyKeyboardMarkup, KeyboardButton, InlineKeyboardButton, InlineKeyboardMarkup

from keyboards import client_kb_uz

ru = KeyboardButton('🇷🇺 Русский')
uz = KeyboardButton("🇺🇿 O'zbek tili")
eng = KeyboardButton('🇬🇧 English')
location = KeyboardButton('🌏Отправить местоположение', request_location=True)
phone = KeyboardButton('📱Отправить номер телефона', request_contact=True)
kafe_1 = KeyboardButton('Яккасарайский р-он, ул. Шарафа Рашидова 40В')
kafe_2 = KeyboardButton('Сергелийский р-он, ул. Обихаёт 3')
delivery = KeyboardButton('🚗Доставка')
self = KeyboardButton('🏢Самовывоз')
piza = KeyboardButton('🍕 Пицца')
salad = KeyboardButton('🥗 Салаты')
souse = KeyboardButton('🧂 Соусы')
snack = KeyboardButton('🍟 Снеки')
drink = KeyboardButton('🥤 Напитки')
mini_pizza = KeyboardButton('🍕 Мини пиццы')
sets = KeyboardButton('🗂 Сеты')
order = KeyboardButton('🛎 Заказать')
myorders = KeyboardButton('📜 Мои заказы')
feedback = KeyboardButton('📞 Обратная связь')
main_menu = KeyboardButton('🔙 В главное меню')
back_to_menu = KeyboardButton('◀ Вернуться в меню')
basket = KeyboardButton('🛒 Корзина')
user_data = KeyboardButton('Мои данные')
continue_order = KeyboardButton('▶️Продолжить оформление заказа')
send_order = KeyboardButton('📤Отправить заказ')
cancel = KeyboardButton('❗Отмена')
clear = KeyboardButton('🌀 Очистить корзину')
make_order = KeyboardButton('👍🏽Оформить заказ')

mark_5 = KeyboardButton('Отлично 🌟🌟🌟🌟🌟')
mark_4 = KeyboardButton('Хорошо 🌟🌟🌟🌟')
mark_3 = KeyboardButton('Нормально 🌟🌟🌟')
mark_2 = KeyboardButton('Так себе 🌟🌟')
mark_1 = KeyboardButton('Плохо 🌟')
mark_none = KeyboardButton('Не хочу')

margarita = KeyboardButton('Маргарита')
chick = KeyboardButton('Курица с грибами')
cheeze = KeyboardButton('Четыре сыра')
pep = KeyboardButton('Пепперони')
kombi = KeyboardButton('Комбинированная')
selfie = KeyboardButton('Селфи')
salam = KeyboardButton('Саламалейкум')
sezar = KeyboardButton('Цезарь')
veg = KeyboardButton('Вегетерианская')
tuna = KeyboardButton('С тунцом')
seafood = KeyboardButton('С морепродуктами')
kebab = KeyboardButton('Шашлык')
burger = KeyboardButton('Пицца-Бургер')

pizasouse = KeyboardButton('Пицца соус')
ketchup = KeyboardButton('Кетчуп')
cheezesouse = KeyboardButton('Сырный')
barby = KeyboardButton('Барбекью')
garlic = KeyboardButton('Сливочно-чесночный')

grecsalat = KeyboardButton('Греческий салат')
sezarsalat = KeyboardButton('Салат Цезарь')

frenchfries = KeyboardButton('Картофель фри')
potato = KeyboardButton('Картофель по деревенски')
nagets = KeyboardButton('Куриные нагетсы')
chkub = KeyboardButton('Сырные кубики')
it_mesh = KeyboardButton('Итальянская мешанина')

pepsi = KeyboardButton('Пепси кола')
water = KeyboardButton('Вода с газом')
sok = KeyboardButton('Соки литровые')
fanta = KeyboardButton('Фанта')

mini_margarita = KeyboardButton('Мини Маргарита')
mini_chick = KeyboardButton('Мини Курица с грибами')
mini_cheeze = KeyboardButton('Мини Четыре сыра')
mini_pep = KeyboardButton('Мини Пепперони')
mini_kombi = KeyboardButton('Мини Комбинированная')
mini_selfie = KeyboardButton('Мини Селфи')
mini_salam = KeyboardButton('Мини Саламалейкум')
mini_sezar = KeyboardButton('Мини Цезарь')
mini_veg = KeyboardButton('Мини Вегетерианская')
mini_tuna = KeyboardButton('Мини С тунцом')
mini_seafood = KeyboardButton('Мини С морепродуктами')
mini_kebab = KeyboardButton('Мини Шашлык')

set_burger_bomba = KeyboardButton('Бомба Бургер')
set_bomba = KeyboardButton('Бомба')

# Inline buttons
inline_to_basket = InlineKeyboardButton('🛒 Добавить в корзину', callback_data='add_pizza_to_cart')
inline_to_basket_other = InlineKeyboardButton('🛒 Добавить в корзину', callback_data='add_other_to_cart')
inline_make_order = InlineKeyboardButton('👍🏽Оформить заказ', callback_data='make_order_ru')
inline_remove = InlineKeyboardButton('❌', callback_data='delete_cart')
inline_size_32 = InlineKeyboardButton('32 см', callback_data='32')
inline_size_36 = InlineKeyboardButton('36 см', callback_data='36')
inline_size_38 = InlineKeyboardButton('38 см', callback_data='38')
inline_size_32_1 = InlineKeyboardButton('✔️32 см', callback_data='32')
inline_size_36_1 = InlineKeyboardButton('✔️36 см', callback_data='36')
inline_size_38_1 = InlineKeyboardButton('✔️38 см', callback_data='38')
inline_dsize_1 = InlineKeyboardButton('1 литр', callback_data='1')
inline_dsize_0_5 = InlineKeyboardButton('0,5 литра', callback_data='0.5')
inline_dsize_1_1 = InlineKeyboardButton('✔1 литр', callback_data='1')
inline_dsize_0_5_1 = InlineKeyboardButton('✔0,5 литра', callback_data='0.5')
inline_plus = InlineKeyboardButton(text='➕', callback_data='plus')
inline_minus = InlineKeyboardButton(text='➖', callback_data='minus')
inline_phone = InlineKeyboardButton('Наш инстаграм', url='https://www.instagram.com/selfie_pizza_uz/')
inline_kb_pizza = InlineKeyboardMarkup().row(inline_size_32, inline_size_36, inline_size_38).row(inline_to_basket)
inline_kb_pizza_32 = InlineKeyboardMarkup().row(inline_size_32_1, inline_size_36, inline_size_38).row(inline_to_basket)
inline_kb_pizza_36 = InlineKeyboardMarkup().row(inline_size_32, inline_size_36_1, inline_size_38).row(inline_to_basket)
inline_kb_pizza_38 = InlineKeyboardMarkup().row(inline_size_32, inline_size_36, inline_size_38_1).row(inline_to_basket)
inline_kb_drink = InlineKeyboardMarkup().row(inline_dsize_0_5, inline_dsize_1).row(inline_to_basket)
inline_kb_pizza_0_5 = InlineKeyboardMarkup().row(inline_dsize_0_5_1, inline_dsize_1).row(inline_to_basket)
inline_kb_pizza_1 = InlineKeyboardMarkup().row(inline_dsize_0_5, inline_dsize_1_1).row(inline_to_basket)
inline_kb_phone = InlineKeyboardMarkup().add(inline_phone)
inline_cart = InlineKeyboardMarkup().row(inline_minus, inline_plus).row(inline_remove)
inline_order = InlineKeyboardMarkup().add(inline_make_order)
inline_kb_salat_snack_souse = InlineKeyboardMarkup().add(inline_to_basket_other)

kb_language = ReplyKeyboardMarkup(resize_keyboard=True)
kb_main = ReplyKeyboardMarkup(resize_keyboard=True)
kb_menu = ReplyKeyboardMarkup(resize_keyboard=True)
kb_pizza = ReplyKeyboardMarkup(resize_keyboard=True)
kb_souse = ReplyKeyboardMarkup(resize_keyboard=True)
kb_salat = ReplyKeyboardMarkup(resize_keyboard=True)
kb_snack = ReplyKeyboardMarkup(resize_keyboard=True)
kb_drink = ReplyKeyboardMarkup(resize_keyboard=True)
kb_mini_pizza = ReplyKeyboardMarkup(resize_keyboard=True)
kb_sets = ReplyKeyboardMarkup(resize_keyboard=True)
kb_phone = ReplyKeyboardMarkup(resize_keyboard=True)
kb_address = ReplyKeyboardMarkup(resize_keyboard=True)
kb_kafe = ReplyKeyboardMarkup(resize_keyboard=True)
kb_mydata = ReplyKeyboardMarkup(resize_keyboard=True)
kb_del_or_self = ReplyKeyboardMarkup(resize_keyboard=True)
kb_cart = ReplyKeyboardMarkup(resize_keyboard=True)
marks = ReplyKeyboardMarkup(resize_keyboard=True)
dont_want = ReplyKeyboardMarkup(resize_keyboard=True)

kb_language.row(ru, uz, eng)
kb_main.add(order).row(myorders, user_data, feedback)
kb_menu.row(main_menu, basket).row(piza, mini_pizza).row(drink, salad).row(souse, snack, sets)
kb_pizza.add(back_to_menu).add(veg, tuna) \
    .add(margarita, chick).add(cheeze, pep) \
    .add(kombi, salam).add(selfie, kebab).row(burger, sezar)

kb_souse.add(back_to_menu).add(pizasouse, ketchup) \
    .add(cheezesouse, barby).add(garlic)

kb_salat.add(back_to_menu).add(grecsalat, sezarsalat)

kb_snack.add(back_to_menu).add(frenchfries, potato).add(nagets, chkub).row(it_mesh)

kb_drink.add(back_to_menu, pepsi).add(water, sok).row(fanta)

kb_mini_pizza.row(back_to_menu, mini_margarita).row(mini_chick, mini_cheeze).row(mini_pep, mini_kombi). \
    row(mini_selfie, mini_salam).row(mini_sezar, mini_veg).row(mini_tuna, mini_kebab)

kb_sets.row(back_to_menu).row(set_burger_bomba, set_bomba)

kb_mydata.add(phone, main_menu)

kb_phone.add(phone, continue_order).row(back_to_menu)

kb_address.add(location, send_order).row(main_menu)

kb_kafe.row(kafe_1, kafe_2).row(main_menu, back_to_menu)

kb_cart.row(make_order).row(clear, back_to_menu)

marks.row(mark_none, mark_5, mark_4).row(mark_3, mark_2, mark_1)

dont_want.add(mark_none)
